USE [master]
GO

/****** Object:  Database [ecomerce]    Script Date: 11/4/2024 1:23:51 PM ******/
CREATE DATABASE [ecomerce]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ecomerce', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\ecomerce.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ecomerce_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\ecomerce_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ecomerce].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ecomerce] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ecomerce] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ecomerce] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ecomerce] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ecomerce] SET ARITHABORT OFF 
GO

ALTER DATABASE [ecomerce] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ecomerce] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ecomerce] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ecomerce] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ecomerce] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ecomerce] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ecomerce] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ecomerce] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ecomerce] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ecomerce] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ecomerce] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ecomerce] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ecomerce] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ecomerce] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ecomerce] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ecomerce] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ecomerce] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ecomerce] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [ecomerce] SET  MULTI_USER 
GO

ALTER DATABASE [ecomerce] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ecomerce] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ecomerce] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ecomerce] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [ecomerce] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ecomerce] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [ecomerce] SET QUERY_STORE = OFF
GO

ALTER DATABASE [ecomerce] SET  READ_WRITE 
GO


